---
- name: Install nginx and npm
  hosts: prod
  vars_files: 
    - common_vars.yml
    - vars/vault.yml

  tasks:
    - name: Ensure NGINX is installed
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags: nginx_install

    - name: Ensure custom NGINX configuration file exists
      copy:
        dest: "{{ nginx_config }}"
        content: |
          server {
            listen 80;
            server_name your_domain_or_ip;

            root {{ current_link }};
            index index.html;

            location / {
              try_files $uri $uri/ =404;
            }
          }
        owner: root
        group: root
        mode: '0644'
      tags: nginx_install

    - name: Enable custom NGINX configuration
      file:
        src: "{{ nginx_config }}"
        dest: "/etc/nginx/sites-enabled/ {{ git_repo_name }}"
        state: link
      notify: Restart NGINX
      tags: nginx_install

    - name: Ensure the backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

  roles:
    - role: ansible-role-nvm
      nodejs_version: "{{ node_version }}"
      nvm_commands:
       - "nvm exec default npm install"
      tags: node_install

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
