---
- name: Deploy Static Next.js Site
  hosts: prod
  vars_files: 
    - vars/common_vars.yml
    - vars/vault.yml
  vars: 
    artifact_list_url: "https://api.github.com/repos/{{ git_username }}/{{ git_repo_name }}/actions/artifacts"

  tasks:
    - name: Check if current_link exists
      stat:
        path: "{{ current_link }}"
      register: current_link_stat

    - name: Create a backup of current static files if they exist
      shell: cp -r $(readlink -f {{ current_link }}) {{ backup_dir }}/app_backup_$(date +%Y%m%d%H%M%S)
      when: current_link_stat.stat.exists
      args:
        executable: /bin/bash

    - name: Get list of artifacts
      shell: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer {{ github_token }}" \
          {{ artifact_list_url }}
      register: artifacts_response

    - name: Extract artifact information
      set_fact:
        artifacts: "{{ artifacts_response.stdout | from_json }}"

    - name: Find the most recent artifact
      set_fact:
        most_recent_artifact: "{{ artifacts.artifacts | sort(attribute='created_at', reverse=true) | first }}"

    - name: Ensure the output directory exists
      file:
        path: "{{ app_dir }}/out/"
        state: directory

    - name: Download most recent artifact
      shell: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer {{ github_token }}" \
          -o {{ app_dir }}/out/artifact.zip \
          {{ most_recent_artifact.archive_download_url }}

    - name: Unzip artifact
      unarchive:
        src: "{{ app_dir }}/out/artifact.zip"
        dest: "{{ app_dir }}/out/"
        remote_src: yes

    - name: Remove existing symbolic link
      file:
        path: "{{ current_link }}"
        state: absent
        force: yes

    - name: Create new symbolic link to the new build
      file:
        src: "{{ app_dir }}/out/"
        dest: "{{ current_link }}"
        state: link

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
