---
- name: Deploy Static Next.js Site
  hosts: prod
  vars_files: 
    - common_vars.yml

  tasks:
    - name: Check if current_link exists
      stat:
        path: "{{ current_link }}"
      register: current_link_stat

    - name: Create a backup of current static files if they exist
      shell: cp -r $(readlink -f {{ current_link }}) {{ backup_dir }}/app_backup_$(date +%Y%m%d%H%M%S)
      when: current_link_stat.stat.exists
      args:
        executable: /bin/bash

    - name: Pull latest code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"

    - name: Install dependencies
      shell: |
        source $HOME/.nvm/nvm.sh
        nvm use 20
        npm install --include=dev
      args:
        executable: /bin/bash
        chdir: "{{ app_dir }}"
      environment:
        NODE_ENV: production

    - name: Build
      shell: |
        source $HOME/.nvm/nvm.sh
        nvm use 20
        npm run build
      args:
        executable: /bin/bash
        chdir: "{{ app_dir }}"
      environment:
        NODE_ENV: production

    - name: Remove existing symbolic link
      file:
        path: "{{ current_link }}"
        state: absent
        force: yes

    - name: Create new symbolic link to the new build
      file:
        src: "{{ app_dir }}/out/"
        dest: "{{ current_link }}"
        state: link

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

# ansible-playbook -i inventory.ini deploy.yml --ask-password