---
- name: Rollback Static Next.js Site
  hosts: prod
  vars_files: 
    - common_vars.yml

  tasks:
    - name: List backup directory contents
      command: ls -l "{{ backup_dir }}"
      register: backup_dir_contents

    - name: Display backup directory contents
      debug:
        var: backup_dir_contents

    - name: Find the latest backup
      find:
        paths: "{{ backup_dir }}"
        patterns: 'app_backup_*'
        age: 0
        age_stamp: mtime
        recurse: no
        file_type: directory
      register: backup_files

    - name: Fail if no backup found
      fail:
        msg: "No backups found in {{ backup_dir }}"
      when: backup_files.matched == 0

    - name: Set the latest backup variable
      set_fact:
        latest_backup: "{{ (backup_files.files | sort(attribute='mtime', reverse=True) | first).path }}"
      when: backup_files.matched > 0

    - name: Remove existing symbolic link
      file:
        path: "{{ current_link }}"
        state: absent
        force: yes

    - name: Create new symbolic link to the latest backup
      file:
        src: "{{ latest_backup }}"
        dest: "{{ current_link }}"
        state: link
      when: backup_files.matched > 0

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted